### ISSUE TITLE
Any hotkeys seem already occupied

### ISSUE THREAD

**Issue by Fry2412** [mrousavy/Hotkeys#1]
No matter which hotkey combination I try, the Contructor throws me an exception that the hotkeys may already be occupied.

```
System.ApplicationException
  HResult=0x80131600
  Nachricht = An unexpected Error occured! (Hotkey may already be in use)
  Quelle = Hotkeys
  Stapelüberwachung:
   bei mrousavy.HotKey.RegisterHotKey()
   bei mrousavy.HotKey..ctor(ModifierKeys modifierKeys, Key key, IntPtr windowHandle, Action`1 onKeyAction)
   bei mrousavy.HotKey..ctor(ModifierKeys modifierKeys, Key key, Window window, Action`1 onKeyAction)
   bei WpfApp1.MainWindow..ctor() in C:\Users\Dominik\source\repos\UeliSharp\WpfApp1\MainWindow.xaml.cs: Zeile28

```

**Comment by MairwunNx** [comment]
@Fry2412 

**+1**, I probably have the same problem, my **Shift** + **Alt** don't work and other combinations ... :( 

Library **good**, but, it reason to look for **another** solution ...

**Comment by mrousavy** [comment]
I can look into this issue sometime later this year, for now, you can try debugging the library up until the Win32 API function `RegisterHotKey(IntPtr hWnd, int id, ModifierKeys fsModifiers, int vk)` in `HotKeyWinApi.cs` and see if you can fix the issue.

Pull requests are always welcome! 👍

**Comment by Fry2412** [comment]
Sorry, nevermind.
Shortly after openening this issue I found out that I had another application using this global shortcut. So my fault.
