### ISSUE TITLE
suggestion to author

### ISSUE THREAD

**Issue by dentistfrankchen** [mrousavy/Hotkeys#3]
You really should tell the users to add "using mrousavy" in their code...
This is my solution to my problem, but I nearly took an hour to find it out...

**Comment by dentistfrankchen** [comment]
And your constructor is a bit misleading. Actually it is not required to be added in users' code.

**Comment by mrousavy** [comment]
You're right, that's a poor namespace choice anyways. I've updated the README for clarity.

> And your constructor is a bit misleading. Actually it is not required to be added in users' code.

What do you mean by that? Of course you need the constructor..?

**Comment by dentistfrankchen** [comment]
no... I do not have to write that line(the constructor) in my program...

**Comment by dentistfrankchen** [comment]
I believe there might be some misunderstandings

**Comment by dentistfrankchen** [comment]
besides， I can see that  you have change the delegate clarification  to the arrow clarification,  which makes it a bit hard to understand for  beginners.( maybe you can consider  add more explanation  to make your demo more beginner friendly)
however，your project is really a good one  and I like it.
you really should let more people know this project, write an answer here https://stackoverflow.com/questions/2450373/set-global-hotkeys-using-c-sharp

**Comment by dentistfrankchen** [comment]
By the way, how to add this dll as reference to uwp? vstudio says it is based on .NET framework...

**Comment by mrousavy** [comment]
Haven't worked with UWP yet, but the Library relies on Functions from the Windows API (user32.dll) as you can see [here](https://github.com/mrousavy/Hotkeys/blob/master/Hotkeys/HotKeyWinApi.cs). 

On a Windows Environment, those should work as expected, what happens if you add the library using NuGet?

**Comment by mrousavy** [comment]
Also, regarding the delegate: If you're not comfortable with lambdas (or "arrow functions"), read [this](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/lambda-expressions).

Delegates are not used very often in this context, whereas lambdas are more common and easier to read, at least in my opinion.

**Comment by dentistfrankchen** [comment]
ok.thx for your reply.
