### ISSUE TITLE
problems with delegate

### ISSUE THREAD

**Issue by dentistfrankchen** [mrousavy/Hotkeys#4]
I tried to add a function to the delegate of your example like this

delegate{
keybd_event(VK_LCONTROL, 0, KEYEVENTF_KEYDOWN, 0);
    keybd_event(A, 0, KEYEVENTF_KEYDOWN, 0);
    keybd_event(A, 0, KEYEVENTF_KEYUP, 0);
    keybd_event(VK_LCONTROL, 0, KEYEVENTF_KEYUP, 0);
}

does not get correct result. why?

I did not use the messagebox in the example. Is that nescessary?

**Comment by mrousavy** [comment]
No, showing a MessageBox is not necessary for this to work.

Could you provide more information? Show me a full code snippet, error messages or anything else.

**Comment by dentistfrankchen** [comment]
I solved this problem by using inputsimulator(although I do not know why)
